### ISSUE TITLE
TO_DO List

### ISSUE THREAD

**Issue by ibrahim-1811** [HBRS-SDP/ss24-multi-robot-task-distribution#1]
- [ ] ## Project Overview

### Description
- [x] [Insert brief description of the project] @ibrahim-1811 

### Objectives
- [x] - [List the main objectives of the project] @ibrahim-1811 @nigitha03 @Keerthans097 

### Scope
- [x] - [Outline the scope of the project, including its boundaries and limitations] @nigitha03 @Keerthans097 

### Deliverables
- [x] - [Enumerate the deliverables expected from the project] @ibrahim-1811 @nigitha03 @Keerthans097 

### Technologies/Tools
- [x] - [List the technologies or tools being used in the project] @ibrahim-1811 

- [x] ## Task Allocation 
### Robots Module Tasks
- [ ] - [ ] [Task 1: Description]
  - [ ] Subtasks:
    - [ ] [Setup the repo and get an understanding of the stack from the coach]
    - [ ] [Set up  robot configs and test run prechecks]
    - [ ] [ mapping of environment]
    - [ ] [ Setting up navigation stack in 1 robot ]
    - [ ] [Multi robot communication establishment]
    - [ ] navigation integration in multi robot
    - [ ] Launch file and stack setup for integration
    - [ ] Test_run
  - [ ] Assigned to: @ibrahim-1811 

- [ ] - [ ] [Task 2: Description]
  - [ ] Subtasks:
    - [ ] [Subtask 1]
    - [ ] [Subtask 2]
    - [ ] ...
  - [ ] Assigned to: @ibrahim-1811 
- [ ] ...

### Task Distributor Module Tasks
- [ ] - [ ] [Task 1: Description]
  - [ ] Subtasks:
    - [ ] [Subtask 1]
    - [ ] [Subtask 2]
    - [ ] ...
  - [ ] Assigned to: @Keerthans097 
- [ ] - [ ] [Task 2: Description]
  - [ ] Subtasks:
    - [ ] [Subtask 1]
    - [ ] [Subtask 2]
    - [ ] ...
  - [ ] Assigned to: @Keerthans097 
- [ ] ...

### Shared Memory Module Tasks
- [ ] - [ ] [Task 1:Initial Understanding and Architecture Design]
  - [ ] Subtasks:
    - [ ] [Set up Git and understand the existing approach]
    - [ ] [Brainstrom on the architecture for shared memory]
    - [ ] [Design a dummy API for this module]
  - [ ] Assigned to: @nigitha03 
- [ ] - [ ] [Task 2: Implement the Module ]
  - [ ] Subtasks:
    - [ ] [Pipelines to get required data]
    - [ ] [Process the input data and store the required information]
    - [ ] [Pipelines for robot to access and update the shared memory]
  - [ ] Assigned to: @nigitha03 
- [ ] ...

- [ ] ## Timeline
[ ] - [ ] [Insert timeline for project milestones, deadlines, and task completion] @ibrahim-1811 @Keerthans097 @nigitha03
