### ISSUE TITLE
Finalize the milestones and Timelines for this project.

### ISSUE THREAD

**Issue by ibrahim-1811** [HBRS-SDP/ss24-multi-robot-task-distribution#5]
- [ ] Project Planning and Requirements Gathering.
  - Duration: 
  - Activities:
    - Define project objectives, scope, and deliverables.
    - Gather requirements from stakeholders.
    - Plan project resources and team assignments.
   
- [ ] System Design and Architecture
   - Duration: 
   - Activities:
     -  task1
     -  task2
- [ ] Software Development Phase
  - Duration: 
  - Activities:
       -  task1
       -  task2
- [ ] Testing Phase
   - Duration: 
   - Activities:
     -  task1
     -  task2

- [ ] Documentation
   - Duration: 
   - Activities:
     -  task1
     -  task2
